version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  node-build:
    steps:
    - run: npm run build
  node-tests:
    steps:
    - run: npm run test

workflows:
  version: 2.1
  test_and_deploy:
  jobs:
    - build
    - test